### ISSUE TITLE
Selector Thunk bug in spectral/multiplier

### ISSUE THREAD

**Issue by rahulmutt** [typelead/eta-benchmarks#5]
```
	Suppressed: java.lang.NoSuchFieldError: x1
		at main.Main.$wmultsys(Main.hs:149)
		at main.Main$ds_sOVB.thunkEnter(Main.hs)
		at eta.runtime.thunk.UpdatableThunk.evaluate(UpdatableThunk.java:24)
		at eta.runtime.thunk.SelectorUpd.thunkEnter(SelectorUpd.java:19)
		at eta.runtime.thunk.UpdatableThunk.evaluate(UpdatableThunk.java:24)
		at base.ghc.Base.map(Base.hs:850)
		at main.Main$sat_sOVR.thunkEnter(Main.hs)
		at eta.runtime.thunk.UpdatableThunk.evaluate(UpdatableThunk.java:24)
		at base.ghc.List.null(List.hs:115)
		at base.ghc.List$null.apply1(List.hs:115)
		at base.ghc.Base$sat_sAH6.thunkEnter(Base.hs:851)
		at eta.runtime.thunk.UpdatableThunk.evaluate(UpdatableThunk.java:24)
		at main.Main.$LrNXBgo5(Main.hs)
		at main.Main.trans(Main.hs:421)
		at main.Main.$wtraceMult(Main.hs:121)
		at main.Main$sat_sP07.thunkEnter(Main.hs)
		at eta.runtime.thunk.UpdatableThunk.evaluate(UpdatableThunk.java:24)
		at ghc_prim.ghc.CString$unpack_s6YI.applyN(CString.hs:138)
		at ghc_prim.ghc.CString$sat_s6YN.thunkEnter(CString.hs:139)
		at eta.runtime.thunk.UpdatableThunk.evaluate(UpdatableThunk.java:24)
		at base.ghc.io.handle.Text.$wa7(Text.hs:586)
		at base.ghc.io.handle.Text.hPutStr2(Text.hs:553)
		at main.Main.main1(Main.hs)
		at main.Main$main1.applyV(Main.hs)
		at eta.runtime.exception.Exception.catch_(Exception.java:129)
		at main.Main.main8(Main.hs)
		at main.Main.DZCmain(Main.hs:95)
		at main.Main$DZCmain.applyV(Main.hs:95)
		at eta.runtime.stg.Closures$EvalLazyIO.enter(Closures.java:104)
		at eta.runtime.stg.Capability.schedule(Capability.java:174)
		at eta.runtime.stg.Capability.scheduleClosure(Capability.java:119)
		at eta.runtime.Runtime.evalLazyIO(Runtime.java:170)
		at eta.runtime.Runtime.main(Runtime.java:163)
		at eta.main.main(Unknown Source)
```

**Comment by rahulmutt** [comment]
Fixed. See related issue on `typelead/eta`.
